project_name = ""
org_id = ""
region = ""
zone = ""
vm_name = ""
public_key_path = ""
username = ""
environment = ""
vm_type = ""
number_of_servers = ""

#Example below
#org_id = "123456789"
#project_name = "ty-project"
#region = "europe-west3"
#zone = "europe-west3-c"
#environment = "tr-"
#TF_VAR_project_name = "tr-jh"
#TF_VAR_region = "us-east1"
#tf_zone = "europe-west3"
#public_key_path = "#######"
#username = "#####"
